services:
  work_space:
    build:
      context: ./work_space
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./../lesson_7/notebooks:/work_dir/notebooks
      - ./../lesson_7/data:/work_dir/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]